Install python code in /usr/lib/mailman getting rid of symlinks from /var/lib/mailman.

diff --git a/core/debian/mailman.init b/core/debian/mailman.init
--- a/core/debian/mailman.init
+++ b/core/debian/mailman.init
@@ -13,72 +13,75 @@
 #
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/var/lib/mailman/bin/mailmanctl
-PIDFILE=/var/lib/mailman/data/master-qrunner.pid
+DAEMON=/usr/lib/mailman/bin/mailmanctl
+PIDFILE=/var/run/mailman/mailman.pid
 NAME=mailman
 DESC="mailman queue runner"
+starterr=/var/log/mailman/startup.err
 
 test -x $DAEMON || exit 0
 
 set -e
 
 case "$1" in
-  start)
-        if [ "$(/var/lib/mailman/bin/list_lists -b | grep ^mailman$ )" = "" ]; then
-            echo "Site list for mailman (usually named mailman) missing"
-            echo "Please create it; until then, mailman will refuse to start"
-            exit 0
+    start)
+        echo -n "Starting $DESC"
+        if $DAEMON -s -q start 2>${starterr}; then
+            echo "."
+        else
+            echo -n " failed because "
+            sed -e "s/Site list is missing: \(.*\)$/of missing site list '\1'./" \
+                <${starterr}
         fi
-        $DAEMON -s start
-	echo "."
-	;;
-  stop)
-        $DAEMON stop
-	echo "."
-	;;
-  reload)
-	#
-	#	If the daemon can reload its config files on the fly
-	#	for example by sending it SIGHUP, do it here.
-	#
-	#	If the daemon responds to changes in its config file
-	#	directly anyway, make this a do-nothing entry.
-	#
-	echo -n "Reloading $DESC configuration..."
-	$DAEMON restart
-	 echo "done."
-  ;;
-  restart|force-reload)
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart".
-	#
-	PID=`cat $PIDFILE 2>/dev/null`
-	echo -n "Restarting $DESC: $NAME"
-        $DAEMON stop
-	if test -n "$PID" && kill -0 $PID 2>/dev/null ; then
-		echo -n "Waiting "
-                for cnt in `seq 1 5`; do
-			sleep 1
-			kill -0 $PID 2>/dev/null || break
-			echo -n "."
-		done;
-		if kill -0 $PID 2>/dev/null ; then
-			echo " Failed"
-		else
-			echo " Done"
-		fi
-	fi
-        $DAEMON start
-	echo "."
-	;;
-  *)
-	N=/etc/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+        rm -f ${starterr}
+        ;;
+    stop)
+        echo -n "Stopping $DESC"
+        $DAEMON -q stop
+        echo "."
+        ;;
+    reload)
+    	#
+    	#	If the daemon can reload its config files on the fly
+    	#	for example by sending it SIGHUP, do it here.
+    	#
+    	#	If the daemon responds to changes in its config file
+    	#	directly anyway, make this a do-nothing entry.
+    	#
+        echo -n "Reloading $DESC configuration..."
+        $DAEMON -q restart
+        echo "done."
+        ;;
+    restart|force-reload)
+    	#
+    	#	If the "reload" option is implemented, move the "force-reload"
+    	#	option to the "reload" entry above. If not, "force-reload" is
+    	#	just the same as "restart".
+    	#
+        PID=`cat $PIDFILE 2>/dev/null`
+        echo -n "Restarting $DESC: $NAME"
+        $DAEMON -q stop
+        if test -n "$PID" && kill -0 $PID 2>/dev/null ; then
+            echo -n "Waiting "
+            for cnt in `seq 1 5`; do
+                sleep 1
+                kill -0 $PID 2>/dev/null || break
+            done;
+            if kill -0 $PID 2>/dev/null ; then
+                echo " Failed"
+            else
+                echo " Done"
+            fi
+        fi
+        $DAEMON -q start
+        echo "."
+        ;;
+    *)
+        N=/etc/init.d/$NAME
+	    # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
+        echo "Usage: $N {start|stop|restart|force-reload}" >&2
+        exit 1
+        ;;
 esac
 
 exit 0
